"""
portal-log-api-skill - 由 Web API 抓取器自动生成
Generated by Genvis Web API Extractor
"""
from fastapi import FastAPI, HTTPException, Query, Header
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Any, Optional
import httpx
import os

app = FastAPI(
    title="portal-log-api-skill",
    description="",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ===== 基础配置 =====
BASE_URL = "https://www.gujing.cn/r/w?sid=41aa34f3-33f8-49d8-a637-31bcd52c39ef&cmd=com.awspaas.user.apps.gujingdaylog_home"

# Cookie 和自定义 Header 配置（可通过环境变量覆盖）
DEFAULT_COOKIES = os.environ.get("API_COOKIES", "")
DEFAULT_HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
    "Accept": "application/json, text/plain, */*",
}


def build_headers(extra: Optional[dict] = None) -> dict:
    """构建请求头，合并默认头和额外头"""
    headers = dict(DEFAULT_HEADERS)
    if DEFAULT_COOKIES:
        headers["Cookie"] = DEFAULT_COOKIES
    if extra:
        headers.update(extra)
    return headers


# ===== 健康检查 =====
@app.get("/health")
async def health_check():
    """健康检查接口"""
    return {"status": "ok", "service": "portal-log-api-skill"}


# ===== 代理接口 =====
class QuerylogRequest(BaseModel):
    creators: Optional[str] = None  # creators
    startDate: Optional[str] = None  # startDate
    endDate: Optional[str] = None  # endDate
    class Config:
        extra = "allow"


@app.post("/querylog", summary="查询日志", tags=["default"])
async def querylog(body: QuerylogRequest):
    """调用 POST /r/jd?cmd=com.awspaas.user.apps.gujingdaylog_querylog"""
    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            resp = await client.post(
                f"{BASE_URL}/r/jd?cmd=com.awspaas.user.apps.gujingdaylog_querylog",
                json=body.model_dump(exclude_none=True),
                headers=build_headers(),
            )
            resp.raise_for_status()
            return resp.json()
    except httpx.HTTPStatusError as e:
        raise HTTPException(status_code=e.response.status_code, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

class LogRequest(BaseModel):
    logId: Optional[str] = None  # logId
    logDate: Optional[str] = None  # logDate
    logLocation: Optional[str] = None  # logLocation
    logContent: Optional[str] = None  # logContent
    isDel: Optional[str] = None  # isDel
    class Config:
        extra = "allow"


@app.post("/log", summary="log", tags=["default"])
async def log(body: LogRequest):
    """调用 POST /r/jd?cmd=com.awspaas.user.apps.gujingdaylog_save_log"""
    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            resp = await client.post(
                f"{BASE_URL}/r/jd?cmd=com.awspaas.user.apps.gujingdaylog_save_log",
                json=body.model_dump(exclude_none=True),
                headers=build_headers(),
            )
            resp.raise_for_status()
            return resp.json()
    except httpx.HTTPStatusError as e:
        raise HTTPException(status_code=e.response.status_code, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("PORT", 8000))
    uvicorn.run(app, host="0.0.0.0", port=port)
